name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Replace API key in gemini-api.js
      run: |
        echo "Replacing API key..."
        if [ -n "${{ secrets.GEMINI_API_KEY }}" ]; then
          sed -i "s/const GEMINI_API_KEY = 'PLACEHOLDER';/const GEMINI_API_KEY = '${{ secrets.GEMINI_API_KEY }}';/g" js/gemini-api.js
          echo "API key replaced successfully"
        else
          echo "Warning: GEMINI_API_KEY secret is not set"
        fi
        
    - name: Verify API key replacement
      run: |
        echo "Checking gemini-api.js content:"
        head -n 5 js/gemini-api.js
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4