name: Lighthouse CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npm run playwright:install

    - name: Build project
      run: |
        npm run build
        npm run update:html

    - name: Start local server
      run: |
        npm run serve &
        sleep 10
      env:
        CI: true

    - name: Wait for server
      run: |
        npx wait-on http://localhost:3000 --timeout 60000

    - name: Run Lighthouse CI
      run: |
        npm install -g @lhci/cli@0.13.x
        lhci autorun
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}

    - name: Run custom performance tests
      run: |
        npm run test:performance
      continue-on-error: true

    - name: Upload Lighthouse reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lighthouse-reports
        path: |
          .lighthouseci/
          lighthouse-reports/
          performance-reports/
        retention-days: 30

    - name: Comment PR with Lighthouse scores
      uses: foo-software/lighthouse-check-action@master
      if: github.event_name == 'pull_request'
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
        author: ${{ github.actor }}
        branch: ${{ github.head_ref }}
        outputDirectory: /tmp/artifacts
        urls: |
          http://localhost:3000
          http://localhost:3000/tests/mbti/
          http://localhost:3000/fortune/daily/
          http://localhost:3000/tools/bmi-calculator.html
        sha: ${{ github.sha }}
        wait: true
        timeout: 600000

    - name: Performance regression check
      run: |
        node scripts/check-performance-regression.js
      continue-on-error: true

  mobile-lighthouse:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npm run playwright:install

    - name: Build project
      run: |
        npm run build
        npm run update:html

    - name: Start local server
      run: |
        npm run serve &
        sleep 10

    - name: Run Mobile Lighthouse CI
      run: |
        npm install -g @lhci/cli@0.13.x
        lhci autorun --config=./lighthouserc-mobile.js
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}

    - name: Upload Mobile Lighthouse reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lighthouse-mobile-reports
        path: |
          .lighthouseci/
          lighthouse-mobile-reports/
        retention-days: 30

  performance-budget:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci

    - name: Build project
      run: |
        npm run build
        npm run update:html

    - name: Check bundle sizes
      run: |
        npm run build:js:analyze
        npx bundlesize

    - name: Performance budget check
      run: |
        node scripts/performance-budget-check.js
      continue-on-error: true

    - name: Generate performance report
      run: |
        node scripts/generate-performance-report.js
      continue-on-error: true

    - name: Upload performance artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: performance-artifacts
        path: |
          bundle-analysis/
          performance-reports/
        retention-days: 30